#gb_louvre_homepage:
 #   path:     /
  #  defaults: { _controller: GBLouvreBundle:Default:index }

gb_louvre_accueil:
    path: /billetterie
    defaults: { _controller: GBLouvreBundle:Louvre:accueil}

gb_louvre_billetterie:
    path: /billetterie/formulaire
    defaults: { _controller: GBLouvreBundle:Louvre:formulaire}


gb_louvre_recapitulatif:
    path: /billetterie/recapitulatif/{id}
    defaults: { _controller: GBLouvreBundle:Louvre:recapitulatif}

order_prepare:
    path: /order/prepare/{id}
    defaults: { _controller: GBLouvreBundle:Louvre:paiement}

order_checkout:
    path: /order/checkout/{id}
    defaults: { _controller: GBLouvreBundle:Louvre:checkout}