services:

#    gb_louvre.example:
#        class: GB\LouvreBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    gb_louvre.calculprixbillet:
        class: GB\LouvreBundle\Calculprixbillet\Calculprixbillet

    gb_louvre.stripe:
        class: GB\LouvreBundle\Stripe\Stripe

    gb_louvre.mail:
        class: GB\LouvreBundle\Mail\Mail
        arguments:
            - "@mailer"
            - "@templating"

    gb_louvre.ajax:
        class: GB\LouvreBundle\Ajax\Ajax
        arguments:
            - "@doctrine.orm.entity_manager"