services:

#    gb_louvre.example:
#        class: GB\LouvreBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    gb_louvre.calculprixbillet:
        class: GB\LouvreBundle\Calculprixbillet\Calculprixbillet